-- MySQL Script generated by MySQL Workbench
-- 02/10/15 13:25:00
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdsm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdsm` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `bdsm` ;

-- -----------------------------------------------------
-- Table `bdsm`.`testado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsm`.`testado` (
  `idestado` CHAR NOT NULL,
  `codigoestado` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `estatusestado` INT NOT NULL,
  PRIMARY KEY (`codigoestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsm`.`tciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsm`.`tciudad` (
  `idciudad` CHAR NOT NULL,
  `codigociudad` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `estatusciudad` VARCHAR(45) NOT NULL,
  `codigoestado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigociudad`),
  INDEX `fk_tciudad_testado1_idx` (`codigoestado` ASC),
  CONSTRAINT `fk_tciudad_testado1`
    FOREIGN KEY (`codigoestado`)
    REFERENCES `bdsm`.`testado` (`codigoestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsm`.`tparroquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsm`.`tparroquia` (
  `idparroquia` CHAR NOT NULL,
  `codigoparroquia` VARCHAR(45) NOT NULL,
  `parroquia` VARCHAR(45) NOT NULL,
  `estatusparroquia` VARCHAR(45) NOT NULL,
  `tciudad_codigociudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoparroquia`),
  INDEX `fk_tparroquia_tciudad1_idx` (`tciudad_codigociudad` ASC),
  CONSTRAINT `fk_tparroquia_tciudad1`
    FOREIGN KEY (`tciudad_codigociudad`)
    REFERENCES `bdsm`.`tciudad` (`codigociudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsm`.`tpersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsm`.`tpersona` (
  `idpersona` CHAR NOT NULL,
  `cedula` VARCHAR(11) NOT NULL,
  `primernombre` VARCHAR(45) NOT NULL,
  `segundonombre` VARCHAR(45) NOT NULL,
  `primerapellido` VARCHAR(45) NOT NULL,
  `segundoapellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(120) NOT NULL,
  `sexo` CHAR NOT NULL,
  `historia` VARCHAR(45) NOT NULL,
  `estatuspersona` INT NOT NULL,
  `motivoconsulta` VARCHAR(45) NOT NULL,
  `codigoparroquia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`),
  INDEX `fk_tpersona_tparroquia1_idx` (`codigoparroquia` ASC),
  CONSTRAINT `fk_tpersona_tparroquia1`
    FOREIGN KEY (`codigoparroquia`)
    REFERENCES `bdsm`.`tparroquia` (`codigoparroquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsm`.`tdepartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsm`.`tdepartamento` (
  `iddepartamento` CHAR NOT NULL,
  `codigodepartamento` VARCHAR(45) NOT NULL,
  `turnodepartamento` VARCHAR(45) NOT NULL,
  `estatusdepartamento` INT NOT NULL,
  PRIMARY KEY (`codigodepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsm`.`ttrabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsm`.`ttrabajador` (
  `idtrabajador` CHAR NOT NULL,
  `codigotrabajador` VARCHAR(45) NOT NULL,
  `estatustrabajador` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(11) NOT NULL,
  `codigodepartamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigotrabajador`),
  INDEX `fk_ttrabajador_tpersona1_idx` (`cedula` ASC),
  INDEX `fk_ttrabajador_tdepartamento1_idx` (`codigodepartamento` ASC),
  CONSTRAINT `fk_ttrabajador_tpersona1`
    FOREIGN KEY (`cedula`)
    REFERENCES `bdsm`.`tpersona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ttrabajador_tdepartamento1`
    FOREIGN KEY (`codigodepartamento`)
    REFERENCES `bdsm`.`tdepartamento` (`codigodepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsm`.`tcarrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsm`.`tcarrera` (
  `idcarrera` CHAR NOT NULL,
  `codcarrera` VARCHAR(45) NOT NULL,
  `carrera` VARCHAR(45) NOT NULL,
  `seccion` CHAR NOT NULL,
  `turnocarrera` VARCHAR(45) NOT NULL,
  `estatuscarrera` INT NOT NULL,
  PRIMARY KEY (`codcarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsm`.`testudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsm`.`testudiante` (
  `idtestudiante` CHAR NOT NULL,
  `codigoestudiante` VARCHAR(45) NOT NULL,
  `estatusestudiante` INT NOT NULL,
  `codcarrera` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(11) NOT NULL,
  INDEX `fk_testudiante_tcarrera1_idx` (`codcarrera` ASC),
  INDEX `fk_testudiante_tpersona1_idx` (`cedula` ASC),
  PRIMARY KEY (`codigoestudiante`),
  CONSTRAINT `fk_testudiante_tcarrera1`
    FOREIGN KEY (`codcarrera`)
    REFERENCES `bdsm`.`tcarrera` (`codcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_testudiante_tpersona1`
    FOREIGN KEY (`cedula`)
    REFERENCES `bdsm`.`tpersona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsm`.`ttiporeferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsm`.`ttiporeferencia` (
  `idtiporeferencia` CHAR NOT NULL,
  `codigotiporeferencia` INT NOT NULL,
  `tiporeferencia` VARCHAR(45) NOT NULL,
  INDEX `idconsulta_idx` (`codigotiporeferencia` ASC),
  PRIMARY KEY (`codigotiporeferencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsm`.`treferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsm`.`treferencia` (
  `idreferencia` CHAR NOT NULL,
  `codigoreferencia` INT NOT NULL,
  `referencia` VARCHAR(45) NOT NULL,
  `treferenciacol` VARCHAR(45) NOT NULL,
  `estatusreferencia` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(11) NOT NULL,
  `codigotiporeferencia` INT NOT NULL,
  PRIMARY KEY (`codigoreferencia`),
  INDEX `fk_treferencia_tpersona1_idx` (`cedula` ASC),
  INDEX `fk_treferencia_ttiporeferencia1_idx` (`codigotiporeferencia` ASC),
  CONSTRAINT `fk_treferencia_tpersona1`
    FOREIGN KEY (`cedula`)
    REFERENCES `bdsm`.`tpersona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_treferencia_ttiporeferencia1`
    FOREIGN KEY (`codigotiporeferencia`)
    REFERENCES `bdsm`.`ttiporeferencia` (`codigotiporeferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
